### ISSUE TITLE
clan cog (trophy requirements/clan tags/) for public 

### ISSUE THREAD

**Issue by Garcia1008** [smlbiobot/SML-Cogs#13]
<img width="691" alt="captura de pantalla 2017-11-21 a la s 22 18 26" src="https://user-images.githubusercontent.com/29993298/33110038-bfa5de62-cf0a-11e7-815c-0a58a37244c7.png">

**Comment by smlbiobot** [comment]
Implemented in https://github.com/smlbiobot/SML-Cogs/commit/2a4441ee84632c2db1daaef21a6ce334d31dc5f9

Added config fields:

1. Description
2. Info field(s) — use one or more if needed.
3. Color in hex for embed

Enhancement:
- If trophy not found in clan description, use CR clan trophy requirements.

Sample YAML:

```yaml
name: Reddit Alpha Clan Family
description: >
  Minimum trophies to join our Clash Royale clans.
  Current trophies required unless PB (personal best) is specified.
color: ff0f37
clans:
  - name: Reddit Alpha
    tag: 2CCCP
  - name: Reddit Bravo
    tag: 2U2GGQJ
  - name: Reddit Charlie
    tag: 2QUVVVP
  - name: Reddit Delta
    tag: Y8GYCGV
  - name: Reddit Echo
    tag: LGVV2CG
  - name: Reddit Foxtrot
    tag: QUYCYV8
  - name: Reddit Golf
    tag: GUYGVJY
  - name: Reddit Hotel
    tag: UGQ28YU
info:
  - name: How to join
    value: >
      If you meet requirements, please request to join in-app.
      Let us know after you have been accepted.
```

Feel free to re-open if needed.
